### ISSUE TITLE
Latest posts on homepage

### ISSUE THREAD

**Issue by ioanrobciuc** [Codeinwp/Medica-Lite#14]
"As vrea sa facem update la temele lite care nu sunt publicate si sa punem pe homepage cumva latest posts .

Ideea e ca eu vreau sa afisam homepage custom by default, dar cum setarea default in wp este : Latest posts, trebuie sa o respectam.

Se pot face mici smecherii de genul : https://wordpress.org/themes/vantage, adica sa pune o mica sectiune cu latest posts undeva .

O sa fac eu asta la Zerif, si ar trebui facut si la Constructzine Lite + temele in asteptare ( medica/denta/mooveit /plumbeit )"

**Comment by robciucioan** [comment]
@ineagu, aici există secțiunea de "latest news" pe prima pagină.
