### ISSUE TITLE
Creare fisier readme

### ISSUE THREAD

**Issue by robi09** [Codeinwp/Medica-Lite#21]
Trebuie sa adaugi link-ul la absolute orice este folosit in tema, js, fonts, images etc.

**Comment by robciucioan** [comment]
@robi09, link-urile de la imaginile de pe http://demo.themeisle.com/medica-lite/ de unde le iau?

**Comment by robi09** [comment]
@robciucioan Pai ai doua variante: 1. poti cauta pe team work 2. Ask the @Oliviu

**Comment by Oliviu** [comment]
@robciucioan Ionut, demo-ul facut de mine a suferit anumite modificari, s-au adaugat si alte imagini.
Poftim linkurile cu toate imaginile folosite de mine: 

http://www.freeimages.com/photo/840600
http://www.freeimages.com/photo/1314902
http://www.freeimages.com/photo/449234
http://www.freeimages.com/photo/473390
http://www.dreamstime.com/hellooo-free-stock-photos-imagefree121048
http://www.freeimages.com/photo/1158336

**Comment by ineagu** [comment]
As evita mai degraba sa folosim imaginile astea, din ce imi dau seama nu sunt GPL

**Comment by robciucioan** [comment]
@ineagu, cum rămâne aici? Folosesc aceste link-uri sau aștept să se facă update la poze?

**Comment by ineagu** [comment]
e ok sa le folosim pe demo, dar tu ai nevoie sa le folosesti in codul temei ?

**Comment by robciucioan** [comment]
@ineagu, păi, acele link-urile alea nu trebuiesc puse în readme.txt?

**Comment by ineagu** [comment]
@robciucioan tre sa punem in readme.txt fisierele care le folosim in tema, nu pe demo.

Daca noi dam tema fara imaginile alea, nu tre sa punem.

**Comment by robciucioan** [comment]
@ineagu, am înțeles. Mersi!
