### ISSUE TITLE
Traducere texte js

### ISSUE THREAD

**Issue by robi09** [Codeinwp/Medica-Lite#23]
Chiar si textele din javascript trebuiesc traduse in felul asta :
http://codex.wordpress.org/I18n_for_WordPress_Developers#Handling_JavaScript_...
http://codex.wordpress.org/I18n_for_WordPress_Developers#Handling_JavaScript_files;,
de ex partea de upgrade to pro in temele lite nu e facuta corect (nu se
poate traduce )

**Comment by robciucioan** [comment]
@robi09 & @ineagu, în această temă nu sunt butoanele "Upgrade" & "Pro" + nici de tradus vreun text JavaScript.

**Comment by ineagu** [comment]
ok, le poti pune + explica si celorlalti de la voi despre cum se face pe
viitor asta :)

2015-01-09 23:57 GMT+01:00 Robciuc Ioan <notifications@github.com>:

**Comment by robciucioan** [comment]
@ineagu, ok.
