### ISSUE TITLE
Fisier readme

### ISSUE THREAD

**Issue by robi09** [Codeinwp/Medica-Lite#28]
Ionut te rog sa faci fisierul readme la aceasta tema.

Demo pentru text: https://github.com/Codeinwp/dentatheme-lite la ultimul punct adaugi creditele ( gen la galeriile js fonturi etc )

**Comment by robi09** [comment]
Adauga link licenta pentru:
https://github.com/Codeinwp/Medica-Lite/blob/development/images/full-header.jpg ( acum am obs ca este deja acel text de licenta in license.txt ).

@ineagu Trebuie neaparat sa fie si readme.txt sau doar license.txt cu toate link-urile necesare ajunge?

**Comment by ineagu** [comment]
Noi in license.txt puneam textul licentei gpl iar in readme licenta elementelor

**Comment by robi09** [comment]
@ionut robciuc ...go for it!

**Comment by robciucioan** [comment]
@robi09, imaginea https://github.com/Codeinwp/Medica-Lite/blob/development/images/full-header.jpg am șters-o din folderul "images" fiindcă nu o foloseam în temă.
