### ISSUE TITLE
Merge CSS

### ISSUE THREAD

**Issue by robi09** [Codeinwp/Medica-Lite#29]
Fa merge la fisierele css din folderul .css ( adica sa le aduni in acelasi fisier )
Vezi ca acolo ai la font-awesome si normal si min, folosesti doar cel min. 
Nu uita sa stergi import-urile din css.

**Comment by robi09** [comment]
Adauga si reset-ul tot aici.

**Comment by robciucioan** [comment]
@robi09, reset.css este în style.css. Am copiat doar font-awesome.min.css.
