### ISSUE TITLE
RECOMMENDED: No reference to add_theme_support( "title-tag" )

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/Medica-Lite#33]
RECOMMENDED: No reference to add_theme_support( "title-tag" ) was found in the theme. It is recommended that the theme implement this functionality for WordPress 4.1 and above.

@robi09 puteti investiga asta ? Toate temele ar trebui sa foloseasca

**Comment by robi09** [comment]
Desigur. 

@robciucioan adauga te rog add_theme_support( "title-tag" ) in aceasta tema, detalii: http://codex.wordpress.org/Function_Reference/add_theme_support#Title_Tag
