### ISSUE TITLE
wp_enqueue_scripts

### ISSUE THREAD

**Issue by robi09** [Codeinwp/Medica-Lite#35]
@ineagu  in functions.php la linia 157 este un wp_enqueue pentru html5shiv, nu ar trebuii pus in functia medica_lite_wp_enqueue_scripts_medica ?

**Comment by ineagu** [comment]
@robi09 ai dreptate dupa cum vezi si prefixul fixurilor e aiurea : 

_s_html5shiv

_s_scripts

eu am dat un exemplu standard, dar se pare ca ionut a dat copy paste ad literam

@robciucioan poti fii mai atent la ce faci ?
