### ISSUE TITLE
Font awesome

### ISSUE THREAD

**Issue by robi09** [Codeinwp/Medica-Lite#38]
Tinand cont de review-ul de la wp.org ar trebuii sa atasezi in tema si font-awesome.dev.css , adica versiunea de css la font awesome normala, fara minfy.

**Comment by robi09** [comment]
#29

**Comment by robciucioan** [comment]
@robi09, în #29 am copiat CSS-ul din "font-awesome.min.css" în "style.css". Trebuie să șterg ce am copiat în "style.css" și să pun link către "font-awesome.min.css" în "functions.php"?
