### ISSUE TITLE
Footer copyright

### ISSUE THREAD

**Issue by robi09** [Codeinwp/Medica-Lite#43]
"Copyright © Movatique is proudly powered by WordPress. "

movatique trebuie sa fie numele site-ului
adauga la sfarsit si Theme: Mooveit Lite.
adauga link pe wordpress catre wordpress si link pe numele temei catre tema
toate textele trebuie sa se poata traduce

**Comment by ineagu** [comment]
asta de ce era la medica ?

**Comment by robciucioan** [comment]
@ineagu, nu înțeleg.

**Comment by robi09** [comment]
Este aceeasi problema si la medica, dar am dat copy-paste si nu am mai schimbat numele temei in textul de issue.
