### ISSUE TITLE
customizer options

### ISSUE THREAD

**Issue by robi09** [Codeinwp/Medica-Lite#59]
- There's a lot of options in the Customizer and it isn't immediately
  obvious where the information entered is going. Could you update your
  documentation?

@ineagu  aici se refera la documentatia temei sau la titlurile din customizer?

**Comment by ineagu** [comment]
la titluri/descriere in customizer. Avem descriere la fields ? l putem grupa mai simplu de inteles, scoate ce nu e nevoie ?

**Comment by robciucioan** [comment]
@robi09, aici cum fac?

**Comment by robi09** [comment]
@robciucioan maine vorbim si iti explic cum trebuie sa le aranjezi si ce trebuie sa contina.

**Comment by ineagu** [comment]
@robi09 @robciucioan ce facem aici ? ar fi trebui sa pun un update astazi ..

A fost rezolvat tot de aici : 

Are the icons you've used from icomoon.io GPL compatible? Please could you provide license details?
Please declare the license for Nivo Lightbox.
Layout issues after assigning a page to be a posts page through Appearance > Customize > Front:
https://cloudup.com/cW5giF6yy5I
Theme URI is still leading to a 404 page:
https://cloudup.com/cOCvjYlSqcy.
One of the WordPress-generated CSS classes that themes need to support is missing: .wp-caption.
I'll carry on to review and post more complete findings either later this evening or tomorrow morning. Thank you so much again for all of your patience.


Some further findings, as promised. Please can you look over these in addition to the above:
As mentioned in the first review, all site information, including the charset, is required to be called using the correct template tag. Could you look at your header.php file and fix this? You can see examples in _s for how the charset should be called:
https://github.com/Automattic/_s/blob/master/header.php
There's a lot of options in the Customizer and it isn't immediately obvious where the information entered is going. Could you update your documentation?
If a user skips entering a link in the Customizer's 'Social icons' section then the incorrect social icon for a link is displayed:
https://cloudup.com/cLA1IIgkekX
Please prefix script handles for medica_lite_wp_enqueue_style_medica and medica_lite_wp_enqueue_style_medica in functions.php.


Mai multe detalii aici : https://themes.trac.wordpress.org/ticket/21740
