### ISSUE TITLE
embed map

### ISSUE THREAD

**Issue by alexandrastann** [Codeinwp/Medica-Lite#96]
it's not working. i tested on my localhost and it's not getting displayed.
http://themeisle.com/forums/topic/location-code/

**Comment by rodica-andronache** [comment]
@alexandrastann te referi la asta http://prntscr.com/8dp5pb ?
Pare sa mearga.. Ai selectat template-ul Contact pt pagina respectiva? Ca in site-ul lui nu pare sa fi facut asta
